### PR TITLE
chore: Making custom resource dependent on eventbridge rule creation

### PR DESCRIPTION
**Pull request by nikhil-zadoo**
* This is to ensure that there is atleast 1 resolver present at all times, so as to not miss the resource create event

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rafaelliu** [comment]
Thanks for catching that, Nikhil! This is failing with:

> Error: Failed to create changeset for the stack: dependency, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Template format error: Unresolved resource dependencies [ParameterRule] in the Resources block of the template

We'll need to use `rSignalFunctionParameterRule` as it is [SAM's generated logical id](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-function.html#sam-specification-generated-resources-function-eventbridge). Can you change and test?

**Comment by nikhil-zadoo** [comment]
Ahhh my bad. I assumed it would do that. Yeah I can fix this :)

**Comment by nikhil-zadoo** [comment]
I have updated the PR with the fix.

**Comment by rafaelliu** [comment]
This fell through the cracks. Merged. Thanks nikhil!

**Pull request merged**
